name: Get and Cached

# actions are not workflows but are used with workflows so they do not need their own trigger
description: This gets the dependencies and cache's them

inputs:
  caching:
    description: 'To cache dependencies or not'
    required: false
    default: 'true'

outputs:
  used-cache:
    description: 'If cache was used'
    value: ${{ steps.install.outputs.cache }}

runs:
  using: 'composite'

  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }} # if we want to use caching, this step will be executed, else it'll be skipped
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' # if we don't want to use caching
      run: |
        npm ci
        echo "cache=${{inputs.caching}}" # output is being set to the value of input just as an example
      # if there is run, then there must be a shell key which specifies what shell the code is run
      shell: bash
